// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DialogHeaderMore: typeof import('./components/dialog-header-more.vue')['default']
    DialogSupportEmail: typeof import('./components/dialog-support-email.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    PageLogin: typeof import('./components/page-login.vue')['default']
    PageLoginVerify: typeof import('./components/page-login-verify.vue')['default']
    PageRecovery: typeof import('./components/page-recovery.vue')['default']
    PageRecoveryGuardian: typeof import('./components/page-recovery-guardian.vue')['default']
    PageRecoveryPassword: typeof import('./components/page-recovery-password.vue')['default']
    PageRecoveryVerify: typeof import('./components/page-recovery-verify.vue')['default']
    PageRegister: typeof import('./components/page-register.vue')['default']
    PageRegisterPassword: typeof import('./components/page-register-password.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpButton: typeof import('./components/up-button.vue')['default']
    UpDialog: typeof import('./components/up-dialog.vue')['default']
    UpFormItem: typeof import('./components/up-form-item.vue')['default']
    UpHeader: typeof import('./components/up-header.vue')['default']
    UpHeaderConnect: typeof import('./components/up-header-connect.vue')['default']
    UpIcon: typeof import('./components/up-icon.vue')['default']
    UpInput: typeof import('./components/up-input.vue')['default']
    UpSign: typeof import('./components/up-sign.vue')['default']
    UpSignCard: typeof import('./components/up-sign-card.vue')['default']
    UpToken: typeof import('./components/up-token.vue')['default']
  }
}

export {}
